### ISSUE TITLE
Deleted and Deceased contacts are included

### ISSUE THREAD

**Issue by philmb** [systopia/de.systopia.birthdays#10]
We just noticed that deleted (merged) contacts are included in the report. Not huge, but a bit confusing at first.

More importantly, this prompted me to check how the report handles Deceased contacts, and I see that they are also included in the report. This is potentially very embarrassing for those who depend on this report to send birthday greetings.

**Comment by philmb** [comment]
As a work-around, one can create a smart group for Deceased contacts and filter the report to not include that group.

**Comment by systopia** [comment]
Hi @philmb. 

Thanks for reporting the issue, I can definitely see how this would be annoying.

I think I fixed the issue and released version ``1.2.alpha1``. Could you please verify that it works for you?

**Comment by philmb** [comment]
What part aren't you sure about? There are two classes of contacts that shouldn't be included but had been: Deceased and Deleted. The 1.2.alpha1 handled Deleted contacts appropriately, but did not change the way Deceased contacts were handled. The line in my above comment makes sure Deceased contacts aren't included in the report.

**Comment by systopia** [comment]
@philmb Sorry, I didn't see the difference between ``is_deceased`` and ``is_deleted``. Probably had the same issue in my comment before. Sorry.

**Comment by systopia** [comment]
moved the ``is_deceased`` part to #12
