### ISSUE TITLE
Repeated names are removed

### ISSUE THREAD

**Issue by tschuettler** [systopia/de.systopia.birthdays#13]
When a `sort_name`, `first_name` or `last_name` is repeated, it is removed from the output:

For drupal-demo data: 
![grafik](https://user-images.githubusercontent.com/19712240/49370361-35ced280-f6f4-11e8-8d30-2a7789e7522a.png)

Contrary to the code comment the check for repetition is actually performed against any previous row.

**Comment by systopia** [comment]
Hi @tschuettler, happy new year! I've merged your code and released it as ``1.3-beta1``. Could you confirm that it works for you?

**Comment by tschuettler** [comment]
Hey @systopia, happy new year. Thanks for merging. It works fine :)

**Comment by systopia** [comment]
Ok, thanks. If I don't get any issue reports for the beta within the next month or so, I'll release it as ``1.3``
