### ISSUE TITLE
Birthday reports stopped working after update CiviCRM

### ISSUE THREAD

**Issue by MartinAbramov** [systopia/de.systopia.birthdays#20]
Hi! I have a problem, after we update CiviCRM from 5.2x.x to version 5.35.1, birthdays reports stopped working. When Im trying to make a report in CiviCRM, it shows me a empty list. We using version 1.1 of your extension.
Thank you!

**Comment by bjendres** [comment]
@MartinAbramov Could you please try with version ``1.4``? See [HERE](https://github.com/systopia/de.systopia.birthdays/releases/tag/1.4)

**Comment by MartinAbramov** [comment]
Could you please give instructions on how to update, so as not to lose any data?
Thank you!

**Comment by bjendres** [comment]
In general you would swap the extension code in the extension folder, and then (as an admin) visit ``civicrm/admin/extensions?reset=1`` - sometimes there is a popup with an additional upgrade job.

If that's over your head, maybe google a more elaborate description or post a question here: https://civicrm.stackexchange.com/

**Comment by MartinAbramov** [comment]
I appreciate it, thank you!

**Comment by bjendres** [comment]
I see you already know the [stackexchange one](https://civicrm.stackexchange.com/questions/39157/after-update-civicrm-birthday-reports-stopped-working) :)

**Comment by bjendres** [comment]
Upgrading is never without risks, though, so make sure you have a backup.

**Comment by MartinAbramov** [comment]
Well thank you!

**Comment by MartinAbramov** [comment]
Hi! I updated extension, now its 1.4, but this is not working :(
Could it be problem in SQL query, thats in "Developer" tab?
![civicrm](https://user-images.githubusercontent.com/79989945/112445106-720c1e00-8d57-11eb-8c10-a39e60ddfaab.PNG)

**Comment by MartinAbramov** [comment]
Hi! We fix it, have edited SQL query, and now its working

**Comment by MartinAbramov** [comment]
From: 
DATE_ADD(contact_civireport.birth_date, INTERVAL YEAR(CURDATE() - INTERVAL 2 DAY) - YEAR(contact_civireport.birth_date) + IF(DAYOFYEAR(CURDATE() - INTERVAL 2 DAY) >= DAYOFYEAR(contact_civireport.birth_date),1,0) YEAR)  >= 20210325000000

To:
WHERE ( CAST(DATE_ADD(contact_civireport.birth_date, INTERVAL YEAR(CURDATE() - INTERVAL 2 DAY) - YEAR(contact_civireport.birth_date) + IF(DAYOFYEAR(CURDATE() - INTERVAL 2 DAY) >= DAYOFYEAR(contact_civireport.birth_date),1,0) YEAR) AS DATETIME) >= 20210329000000) AND ( CAST(DATE_ADD(contact_civireport.birth_date, INTERVAL YEAR(CURDATE() - INTERVAL 2 DAY) - YEAR(contact_civireport.birth_date) + IF(DAYOFYEAR(CURDATE() - INTERVAL 2 DAY) >= DAYOFYEAR(contact_civireport.birth_date),1,0) YEAR) AS DATETIME) <= 20210329235959) AND  contact_civireport.id IN (

**Comment by bjendres** [comment]
Great stuff! Could you put this in a PR please?

**Comment by MartinAbramov** [comment]
Yes of course, How can i do it?

**Comment by bjendres** [comment]
> Yes of course, How can i do it?

Excellent, thank you! It's quite simple: you fork the repository (using the button top right) which creates a copy of the extension on your own github account. There you can then edit the files, and when you're done you can create a pull request (PR). See e.g. https://opensource.com/article/19/7/create-pull-request-github

**Comment by aydun** [comment]
Please test https://github.com/systopia/de.systopia.birthdays/pull/23 and see if that also fixes your problem.

**Comment by aydun** [comment]
@MartinAbramov did you test the PR to see if it fixes your problem?

**Comment by jofranz** [comment]
Sorry for the delay. We are currently working on this extension.

@MartinAbramov @aydun Could you guys report if PR #23 fixes this problem?

**Comment by MartinAbramov** [comment]
Hi! Sorry I didnt see your messages, yes we fixed it! Than you!

**Comment by jofranz** [comment]
This went into master and is listed in the "tags" section. Thanks for reporting!
