### ISSUE TITLE
Birthdays for today and tomorrow are not shown

### ISSUE THREAD

**Issue by Detsieber** [systopia/de.systopia.birthdays#4]
Strangely, the birthdays are filtered start with 2 days in the future.
Birthdays of "today" and "tomorrow" are not displayed.

**Comment by systopia** [comment]
@Detsieber: Could you test with https://github.com/systopia/de.systopia.birthdays/tree/dev_4 ?

**Comment by Detsieber** [comment]
With dev_4 it works correctly.
Thanks for the quick fix!

**Comment by systopia** [comment]
released with version 1.0
