### ISSUE TITLE
Feature request: More Filters

### ISSUE THREAD

**Issue by Steve4ASU** [systopia/de.systopia.birthdays#5]
Nice extension. I'd like to be able to filter by Contact Type and Contact Sub-type. Plus it would be nice to filter by the month and day of the Birthdate so you could see upcoming birthdays 30- or 60-days out.

**Comment by systopia** [comment]
Hi @Steve4ASU. Thanks. 

I created ticket https://github.com/systopia/de.systopia.birthdays/issues/6 for the contact type filter, that sounds handy.

However I don't understand the "filter by month" idea. Would you like to be able to say "only Feb and Mar"? What if somebody opens the report in April? 

Or do you mean upcoming x days? In that case we'd already have a ticket for that: https://github.com/systopia/de.systopia.birthdays/issues/1

**Comment by Steve4ASU** [comment]
Sorry, yes I meant x days. Didn’t see that earlier ticket.

But to also filter by Groups would be good, too. : )

**Comment by systopia** [comment]
@Steve4ASU: I added that to #6 as well. Thanks.
